apiVersion: v1
kind: Service
metadata:
  name: mconnect
spec:
  selector:
    app: mconnect
  ports:
  - name: tcp
    port: 5001
  - name: udp
    port: 5002
    targetPort: 5001
    protocol: UDP
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mconnect-deployment
spec:
  selector:
    matchLabels:
      app: mconnect
  replicas: 4
  template:
    metadata:
      labels:
        app: mconnect
    spec:
      containers:
      - name: mconnect
        image: nordixorg/mconnect:1.1
        ports:
        - containerPort: 5001
